name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  # workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: a4b3a4759940b83d24430c2c6ddab326
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIMEZONE: Asia/Seoul
